diff --git a/python-api/Dockerfile b/python-api/Dockerfile
index 385ccd3..c59484a 100644
--- a/python-api/Dockerfile
+++ b/python-api/Dockerfile
@@ -6,7 +6,6 @@ COPY requirements.txt .
 RUN pip install --no-cache-dir -r requirements.txt
 
 COPY . .
-
-EXPOSE 8000
+############EXPOSE 8000
 
 CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
